name: RedCable
main: org.ccdd.redcable.RedCable
version: 0.0.1
description: Better RedStone Wires
website: http://dev.bukkit.org/server-mods//
authors: [Chris Churchwell (thedudeguy), DemmyDemon]
database: false
depend: [Spout]